### ISSUE TITLE
getWorksheets couse IndexOutOfRange exception

### ISSUE THREAD

**Issue by red55** [igorkulman/ExcelPackageF#1]
Dear @igorkulman 
Sheet indexing starts at 0 and ends at xlPackage.Workbook.Worksheets.Count - 1
https://github.com/igorkulman/ExcelPackageF/blob/ca3a08aaa9b5be5a15967cf657021c12e7c3d636/ExcelPackageF/ExcelPackageF.fs#L35

Please fix. Thanks!

**Comment by igorkulman** [comment]
I have not touched the code in 4 years, but adding this unit test

```fsharp
[<Test>]
member x.``There should be 3 worksheets`` () =
    let worksheets = 
        fullPath
        |> Excel.getWorksheets
        |> Seq.toArray
    Assert.AreEqual(worksheets.Length,3)
```

that uses the code you mention works fine, I get 3 worksheets as expected in the test XLSX file in this repo. 

But I have noticed that if you  provide an invalid file path to the XSLX file you do not get an exception but 0 worksheets resulting in out of range exception on access.
